Repository oUF-wow/oUF, pull requests merged in 2019-06, with the labels that each got.

#501 tags: Update the system
  elements/tags.lua
Labels: element, feature

#504 Use upstream version of the packager
  .travis.yml
Labels: meta

#506 blizzard: Do not re-parent nameplates
  blizzard.lua
Labels: core

#508 blizzard: Do not hook nameplates' scripts more than once
  blizzard.lua
Labels: bug
