Repository oUF-wow/oUF, pull requests merged in 2021-08, with the labels that each got.

#522 core: add a combat log event system
  combatevents.lua
  oUF.xml
Labels: core

#586 Update packager version
  .github/workflows/release.yml
Labels: tooling

#585 Update Interface version
  oUF.toc
Labels: meta

#584 classpower: Fix chargedPoints unpacking
  elements/classpower.lua
Labels: element, bug

#587 Update LICENSE
  LICENSE
Labels: meta

#588 Add workflow to automatically update license
  .github/workflows/license.yml
Labels: tooling

#582 Keep Aspect Ratio
  elements/auras.lua
Labels: element, feature

#557 Lint
  .editorconfig
  .gitattributes
  .github/workflows/lint.yml
  .luacheckrc
  blizzard.lua
  colors.lua
  elements/additionalpower.lua
  elements/auras.lua
  elements/castbar.lua
  elements/classpower.lua
  elements/health.lua
  elements/powerprediction.lua
  elements/readycheckindicator.lua
  elements/stagger.lua
  elements/tags.lua
  events.lua
  factory.lua
  finalize.lua
  init.lua
  ouf.lua
  private.lua
  units.lua
Labels: tooling

#591 Disable color output from luacheck
  .github/workflows/lint.yml
Labels: bug, tooling

#593 tags: Use UnitEffectiveLevel instead of UnitLevel
  elements/tags.lua
Labels: element, bug
