Repository oUF-wow/oUF, pull requests merged in 2023-11, with the labels that each got.

#660 10.2
  colors.lua
Labels: core, element

#663 Update Interface version
  oUF.toc
Labels: core

#664 healthprediction: Fix unwanted statusbar behaviour
  elements/healthprediction.lua
Labels: element, blizzard bug
